{"name": "Failed login with incorrect username", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 86, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678809246453, "stop": 1678809248690}, {"name": "When I enter an invalid username and a valid password", "status": "passed", "start": 1678809248690, "stop": 1678809249929}, {"name": "And I click on the login button", "status": "passed", "start": 1678809249930, "stop": 1678809250498}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 86, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "attachments": [{"name": "Captura de pantalla", "source": "05f25015-4089-4e82-b573-ef49ec5d19c9-attachment.png", "type": "image/png"}], "start": 1678809250498, "stop": 1678809261596}], "start": 1678809246451, "stop": 1678809261597, "uuid": "f17a0b1a-6b4b-4232-bc19-39af1b76a5f7", "historyId": "1c7c1fda3b6832c4202fcb0ba6646cb6", "fullName": "Login: Failed login with incorrect username", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}