{"name": "Failed login with incorrect username", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 88, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 32, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1679959788667, "stop": 1679959793029}, {"name": "When I enter an invalid username and a valid password", "status": "passed", "start": 1679959793029, "stop": 1679959794312}, {"name": "And I click on the login button", "status": "passed", "start": 1679959794312, "stop": 1679959794874}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 88, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 32, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "attachments": [{"name": "Captura de pantalla", "source": "7450a696-4d6a-4905-9d92-c1098a4bc102-attachment.png", "type": "image/png"}], "start": 1679959794875, "stop": 1679959805374}], "start": 1679959788667, "stop": 1679959805374, "uuid": "e03fb26c-059a-4183-b06b-4cbcd8c6c085", "historyId": "1c7c1fda3b6832c4202fcb0ba6646cb6", "fullName": "Login: Failed login with incorrect username", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}