{"name": "Failed login with incorrect username", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_registrado'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 90, in step_impl\n    usuario = context.config.userdata['usuario_registrado']\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678808330090, "stop": 1678808334230}, {"name": "When I enter an invalid username and a valid password", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_registrado'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 90, in step_impl\n    usuario = context.config.userdata['usuario_registrado']\n"}, "start": 1678808334230, "stop": 1678808334231}, {"name": "And I click on the login button", "status": "skipped", "start": 1678808334232, "stop": 1678808334232}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "skipped", "start": 1678808334232, "stop": 1678808334232}], "start": 1678808330089, "stop": 1678808334232, "uuid": "8d65df51-eb88-4a41-a905-d736e19e215f", "historyId": "1c7c1fda3b6832c4202fcb0ba6646cb6", "fullName": "Login: Failed login with incorrect username", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}