{"name": "Failed login with incorrect username and password", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_invalido'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 62, in step_impl\n    usuario = context.config.userdata['usuario_invalido']\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678808320829, "stop": 1678808325957}, {"name": "When I enter an invalid username and password", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_invalido'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 62, in step_impl\n    usuario = context.config.userdata['usuario_invalido']\n"}, "start": 1678808325957, "stop": 1678808325958}, {"name": "And I click on the login button", "status": "skipped", "start": 1678808325958, "stop": 1678808325958}, {"name": "Then I should see an error message \"Please enter a valid email address.\" indicating that the credentials are incorrect", "status": "skipped", "start": 1678808325958, "stop": 1678808325958}], "start": 1678808320828, "stop": 1678808325958, "uuid": "bc1bf9e1-200d-4f53-a62b-c537383176e4", "historyId": "cda3c4908154763c4fbd814d69ab08c3", "fullName": "Login: Failed login with incorrect username and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}