{"name": "Failed login with incorrect password", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_registrado'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 79, in step_impl\n    usuario = context.config.userdata['usuario_registrado']\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678808325960, "stop": 1678808330084}, {"name": "When I enter my valid username and an invalid password", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_registrado'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 79, in step_impl\n    usuario = context.config.userdata['usuario_registrado']\n"}, "start": 1678808330084, "stop": 1678808330086}, {"name": "And I click on the login button", "status": "skipped", "start": 1678808330087, "stop": 1678808330087}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "skipped", "start": 1678808330087, "stop": 1678808330087}], "start": 1678808325959, "stop": 1678808330087, "uuid": "d4859440-813a-4d56-b745-094dbefd736f", "historyId": "86f143c1ecaca072e529a87c9b79271a", "fullName": "Login: Failed login with incorrect password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}