{"name": "Failed login with incorrect username", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 78, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 30, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1679682642449, "stop": 1679682647822}, {"name": "When I enter an invalid username and a valid password", "status": "passed", "start": 1679682647822, "stop": 1679682649148}, {"name": "And I click on the login button", "status": "passed", "start": 1679682649149, "stop": 1679682649711}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 78, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 30, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "attachments": [{"name": "Captura de pantalla", "source": "340d94a6-f491-4949-b9ba-864ac7ad4855-attachment.png", "type": "image/png"}], "start": 1679682649711, "stop": 1679682660238}], "start": 1679682642449, "stop": 1679682660238, "uuid": "8275fe7f-2e1e-4498-84ed-e91d93df56f9", "historyId": "1c7c1fda3b6832c4202fcb0ba6646cb6", "fullName": "Login: Failed login with incorrect username", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}