{"name": "Failed login with incorrect password", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id=\"next\" type=\"submit\" form=\"localAccountForm\">...</button> is not clickable at point (890, 608). Other element would receive the click: <div class=\"buttons\">...</div>\n  (Session info: chrome=110.0.5481.180)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00DA37D3]\n\t(No symbol) [0x00D38B81]\n\t(No symbol) [0x00C3B36D]\n\t(No symbol) [0x00C74E3B]\n\t(No symbol) [0x00C726DB]\n\t(No symbol) [0x00C6FD0B]\n\t(No symbol) [0x00C6E4D8]\n\t(No symbol) [0x00C63253]\n\t(No symbol) [0x00C8B41C]\n\t(No symbol) [0x00C62B96]\n\t(No symbol) [0x00C8B774]\n\t(No symbol) [0x00CA1215]\n\t(No symbol) [0x00C8B216]\n\t(No symbol) [0x00C60D97]\n\t(No symbol) [0x00C6253D]\n\tGetHandleVerifier [0x0101ABF2+2510930]\n\tGetHandleVerifier [0x01048EC1+2700065]\n\tGetHandleVerifier [0x0104C86C+2714828]\n\tGetHandleVerifier [0x00E53480+645344]\n\t(No symbol) [0x00D40FD2]\n\t(No symbol) [0x00D46C68]\n\t(No symbol) [0x00D46D4B]\n\t(No symbol) [0x00D50D6B]\n\tBaseThreadInitThunk [0x767E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x779F7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x779F7B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 72, in step_impl\n    f.Click(\"id\", \"next\", t)\n  File \"C:\\Repo\\Selenium\\Maquina_uno\\MV1\\Login\\features\\Base_page.py\", line 75, in Click\n    val.click()\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 93, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 403, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678811790517, "stop": 1678811792422}, {"name": "When I enter my valid username and an invalid password", "status": "passed", "start": 1678811792423, "stop": 1678811793711}, {"name": "And I click on the login button", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button id=\"next\" type=\"submit\" form=\"localAccountForm\">...</button> is not clickable at point (890, 608). Other element would receive the click: <div class=\"buttons\">...</div>\n  (Session info: chrome=110.0.5481.180)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00DA37D3]\n\t(No symbol) [0x00D38B81]\n\t(No symbol) [0x00C3B36D]\n\t(No symbol) [0x00C74E3B]\n\t(No symbol) [0x00C726DB]\n\t(No symbol) [0x00C6FD0B]\n\t(No symbol) [0x00C6E4D8]\n\t(No symbol) [0x00C63253]\n\t(No symbol) [0x00C8B41C]\n\t(No symbol) [0x00C62B96]\n\t(No symbol) [0x00C8B774]\n\t(No symbol) [0x00CA1215]\n\t(No symbol) [0x00C8B216]\n\t(No symbol) [0x00C60D97]\n\t(No symbol) [0x00C6253D]\n\tGetHandleVerifier [0x0101ABF2+2510930]\n\tGetHandleVerifier [0x01048EC1+2700065]\n\tGetHandleVerifier [0x0104C86C+2714828]\n\tGetHandleVerifier [0x00E53480+645344]\n\t(No symbol) [0x00D40FD2]\n\t(No symbol) [0x00D46C68]\n\t(No symbol) [0x00D46D4B]\n\t(No symbol) [0x00D50D6B]\n\tBaseThreadInitThunk [0x767E00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x779F7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x779F7B8E+238]\n\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 72, in step_impl\n    f.Click(\"id\", \"next\", t)\n  File \"C:\\Repo\\Selenium\\Maquina_uno\\MV1\\Login\\features\\Base_page.py\", line 75, in Click\n    val.click()\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 93, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 403, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1678811793712, "stop": 1678811794751}, {"name": "Then I should see an error message Your password is incorrect indicating that the your password is incorrect", "status": "skipped", "start": 1678811794752, "stop": 1678811794752}], "start": 1678811790517, "stop": 1678811794752, "uuid": "5bbaf6da-6263-4e5a-8780-224170f75312", "historyId": "86f143c1ecaca072e529a87c9b79271a", "fullName": "Login: Failed login with incorrect password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}