{"name": "Failed login with incorrect password", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 87, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678730371344, "stop": 1678730373337}, {"name": "When I enter my valid username and an invalid password", "status": "passed", "start": 1678730373338, "stop": 1678730374679}, {"name": "And I click on the login button", "status": "passed", "start": 1678730374679, "stop": 1678730375255}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 87, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[2]\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "attachments": [{"name": "Captura de pantalla", "source": "cfa28459-7db8-40e7-bb72-d90d96c81e96-attachment.png", "type": "image/png"}], "start": 1678730375256, "stop": 1678730385890}], "start": 1678730371343, "stop": 1678730385890, "uuid": "a137d56f-01bc-40ad-a6cb-ce2acec9896d", "historyId": "86f143c1ecaca072e529a87c9b79271a", "fullName": "Login: Failed login with incorrect password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}