{"name": "Failed login with incorrect username", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'Navegar'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 9, in step_impl\n    context.Navegar(\"https://yellowpush.b2clogin.com/yellowpush.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?client_id=87a9c1f5-2d71-4c36-8357-4f25c438d63b&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&client-request-id=a77eb88a-459d-414b-b314-e0cdbaaf70ab&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.16.1&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=KzFFackqksd4T_T4M7hmgKo6xyAOupG9tt3lZOxBgCo&code_challenge_method=S256&nonce=cd664f79-cfe1-4eab-a0be-8e10d4f05000&state=eyJpZCI6ImFjNzE2YWIwLWNlMTgtNDFjMC1iYmY1LWE1NjAzZGM0ZDZlYSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D\", 3)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given I am on the login page", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'Navegar'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 9, in step_impl\n    context.Navegar(\"https://yellowpush.b2clogin.com/yellowpush.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?client_id=87a9c1f5-2d71-4c36-8357-4f25c438d63b&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&client-request-id=a77eb88a-459d-414b-b314-e0cdbaaf70ab&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.16.1&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=KzFFackqksd4T_T4M7hmgKo6xyAOupG9tt3lZOxBgCo&code_challenge_method=S256&nonce=cd664f79-cfe1-4eab-a0be-8e10d4f05000&state=eyJpZCI6ImFjNzE2YWIwLWNlMTgtNDFjMC1iYmY1LWE1NjAzZGM0ZDZlYSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D\", 3)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "start": 1678728566769, "stop": 1678728566770}, {"name": "When I enter an invalid username and a valid password", "status": "skipped", "start": 1678728566770, "stop": 1678728566770}, {"name": "And I click on the login button", "status": "skipped", "start": 1678728566770, "stop": 1678728566770}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "skipped", "start": 1678728566770, "stop": 1678728566770}], "start": 1678728566769, "stop": 1678728566770, "uuid": "83656c6a-8a21-486d-9a16-b650ff892175", "historyId": "1c7c1fda3b6832c4202fcb0ba6646cb6", "fullName": "Login: Failed login with incorrect username", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}