{"name": "Failed login with incorrect username", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_registrado'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 90, in step_impl\n    usuario = context.config.userdata['usuario_registrado']\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678805082112, "stop": 1678805085831}, {"name": "When I enter an invalid username and a valid password", "status": "broken", "statusDetails": {"message": "KeyError: 'usuario_registrado'\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 90, in step_impl\n    usuario = context.config.userdata['usuario_registrado']\n"}, "start": 1678805085831, "stop": 1678805085832}, {"name": "And I click on the login button", "status": "skipped", "start": 1678805085833, "stop": 1678805085833}, {"name": "Then I should see an error message We canÂ´t seem to find your account indicating that the user account was not found", "status": "skipped", "start": 1678805085833, "stop": 1678805085833}], "start": 1678805082110, "stop": 1678805085833, "uuid": "b4d7ff83-ca3c-4a09-92c3-75848b817143", "historyId": "1c7c1fda3b6832c4202fcb0ba6646cb6", "fullName": "Login: Failed login with incorrect username", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}