{"name": "Failed login with incorrect username and password", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 76, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[3]/div[1]/div/p\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678733790520, "stop": 1678733795512}, {"name": "When I enter an invalid username and password", "status": "passed", "start": 1678733795512, "stop": 1678733796860}, {"name": "And I click on the login button", "status": "passed", "start": 1678733796860, "stop": 1678733797419}, {"name": "Then I should see an error message \"Please enter a valid email address.\" indicating that the credentials are incorrect", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 76, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[3]/div[1]/div/p\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "attachments": [{"name": "Captura de pantalla", "source": "9a18e3ef-b068-49bc-a69c-98fae0665874-attachment.png", "type": "image/png"}], "start": 1678733797419, "stop": 1678733808072}], "start": 1678733790519, "stop": 1678733808073, "uuid": "0d333e36-7199-44dc-a12b-f9aebcefd457", "historyId": "cda3c4908154763c4fbd814d69ab08c3", "fullName": "Login: Failed login with incorrect username and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}