{"name": "Failed login with incorrect username and password", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 76, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[3]/div[1]/div/p\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1678730174273, "stop": 1678730179330}, {"name": "When I enter an invalid username and password", "status": "passed", "start": 1678730179330, "stop": 1678730180741}, {"name": "And I click on the login button", "status": "passed", "start": 1678730180741, "stop": 1678730181302}, {"name": "Then I should see an error message \"Please enter a valid email address.\" indicating that the credentials are incorrect", "status": "failed", "statusDetails": {"message": "AssertionError: El mensaje de error no coincide\n", "trace": "  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\repo\\selenium\\maquina_uno\\mv1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_login.py\", line 76, in step_impl\n    obtener_mensaje_error(\"//*[@id='localAccountForm']/div[3]/div[1]/div/p\",error_message)\n  File \"features\\steps\\steps_login.py\", line 33, in obtener_mensaje_error\n    raise AssertionError(\"El mensaje de error no coincide\")\n"}, "attachments": [{"name": "Captura de pantalla", "source": "99bf86eb-d038-4078-8c84-1a375eaa6c73-attachment.png", "type": "image/png"}], "start": 1678730181302, "stop": 1678730191983}], "start": 1678730174273, "stop": 1678730191983, "uuid": "4270f475-ac32-4987-8dc3-1cb81f2fd7ca", "historyId": "cda3c4908154763c4fbd814d69ab08c3", "fullName": "Login: Failed login with incorrect username and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}